### ISSUE TITLE
testNonFiniteDurationDoesNotTrap depends on DNS resolution latency

### ISSUE THREAD

**Issue by gewill** [gewill/iperf-swift#150]
## Summary

`testNonFiniteDurationDoesNotTrap` (`IperfSwiftUnitTests.swift:787`) waits two seconds for a run against `invalid.invalid` to fail. It relies on DNS resolution failing quickly, which is incidental to what the test verifies, and on CI it does not always hold.

Filed to record the diagnosis rather than to claim urgency: this is the first occurrence, and a re-run passed. The point is that the dependency is unnecessary, so it can be removed rather than tolerated.

## Evidence

| Run | Result |
| --- | --- |
| https://github.com/gewill/iperf-swift/actions/runs/32847538418 (#148) | both configurations timed out; the test took 4.54s |
| https://github.com/gewill/iperf-swift/actions/runs/32838774530 (#143) | passed in **0.012s** |
| locally, 8 consecutive runs | all passed |

```
IperfSwiftUnitTests.swift:804: error: -[IperfSwiftUnitTests testNonFiniteDurationDoesNotTrap] :
Asynchronous wait failed: Exceeded timeout of 2 seconds, with unfulfilled expectations:
"non-finite duration 0 fails normally".
```

0.012s against >2s is not incremental load on a busy runner — it is the resolver stalling. The failure is unrelated to the change under test in #148, which only touched `IperfIntervalResult.averageRtt`.

## Why the dependency is incidental

The test exists to prove that applying a non-finite `duration` does not trap. `durationSeconds` maps `.infinity` and `.nan` to `0` (`IperfRunner.swift:416`), and `endConditionError` skips its range check for a non-finite value, so such a configuration passes preflight and reaches `applyConfiguration` — where a careless `Int32(...)` conversion would crash the process rather than fail an assertion. That is a real thing to guard, and it is why the test starts a runner at all instead of only calling the converter. The conversion in isolation is already covered by `testDurationConversionMatchesCLIIntegerSemantics` (`IperfSwiftUnitTests.swift:808`).

Reaching that code path needs the run to fail *somehow*. It does not need the failure to come from DNS.

Worth noting for scope: `invalid.invalid` appears about eleven times in the unit tests as a "this configuration must be rejected" placeholder, but almost all of those expect a preflight error — block size, MSS, ToS, reporter interval — and are rejected before any name is resolved. `testNonFiniteDurationDoesNotTrap` is the one that lets the run reach the network, so it is the one exposed to resolver latency.

## Suggested change

Give the test a failure that costs nothing and cannot stall: loopback with a port nothing is listening on, which fails immediately with `ECONNREFUSED` and never consults a resolver.

```swift
private func unreachableClientConfiguration() -> IperfConfiguration {
    var configuration = IperfConfiguration()
    // Loopback with a closed port fails immediately and, unlike an
    // unresolvable name, does not depend on resolver latency.
    configuration.address = "127.0.0.1"
    configuration.port = <a reliably closed port>
    return configuration
}
```

Two things to settle when implementing:

- **Picking the port.** `TestTools.freePort()` lives in the CLI integration tests and throws `XCTSkip` when `iperf3` is absent, so the unit tests should not depend on it. Either add a small local helper that binds and closes a socket to obtain a known-free port, or use a low port that nothing plausibly listens on and accept the small risk.
- **Whether to change the shared helper or only this test.** The helper's other callers never resolve the name, so changing it in place is safe, but it would make the name `unreachableClientConfiguration` slightly less apt — those callers want "a configuration that gets rejected", not "an unreachable host".

Alternatively, raising the timeout would paper over it. That is worse: it keeps a network dependency in a unit test whose subject is an integer conversion, and only widens the window before the same stall fails again.

## Environment

- IperfSwift 3.21.15 (`develop` also carries the unreleased #143, #145 and #147 work)
- Fails on GitHub-hosted macOS runners; not reproducible locally
